### ISSUE TITLE
Cannot submit contract execution successfully

### ISSUE THREAD

**Issue by t-cun** [laalaguer/thor-requests#2]
Hi, I'm trying to follow the `Execute a Function (spend real gas)` example from the README however I'm having an issue submitting the tx.

```
from thor_requests.connect import Connect
from thor_requests.wallet import Wallet
from thor_requests.contract import Contract
connector = Connect("http://mainnet.veblocks.net")
_wallet = Wallet.fromPrivateKey(XXX) 
_contract = Contract.fromFile("./bin/contracts/contract.json")
_contract_addr = '0xblah'
# Execute the "deposit()" function. (will pay gas)
res = connector.transact(_wallet, _contract, "setInitialOwners", [], to=_contract_addr, value=0, gas=60000000)
print(res)
```

I was able to deploy my contract using the example however when attempting to call the `transact` function I'm receiving the following error: `Exception: HTTP error: 400 body: json: cannot unmarshal string into Go struct field BatchCallData.gas of type uint64`

If I update the `connector.transact` call by removing `gas=`, and re-run my script, I get the following error as well (which may be expected as I haven't provided a gas limit):
`Exception: Tx will revert: [{'data': '0x', 'events': [], 'transfers': [], 'gasUsed': 50000000, 'reverted': True, 'vmError': 'out of gas'}]`

I'm not sure if this is an issue with the mainnet.veblocks.net mishandling the request, or the library itself. Any help is appreciated. Thanks in advance!

**Comment by laalaguer** [comment]
Hi, your error is from using the API on veblocks but it didn't response JSON (perhaps hit a limit wall and Cloudflare triggers)
